const popularGames = [
  {
    title: "Пополнение Steam",
    image: require("./Images/div.pop-card.png"),
    price: 150,
    priceLabel: "от 150 руб",
    platform: "Steam/PC",
    genre: "Сервис",
    category: "Игры",
    rating: "12+",
    purchaseOptions: [
      { label: "150 руб", price: 150 },
      { label: "300 руб", price: 300 },
      { label: "600 руб", price: 600 },
    ],
    description:
      "Пополнение баланса Steam для покупок в магазине и внутриигровых товаров.",
    reviews: [
      {
        name: "Алексей М.",
        date: "2026-01-15",
        rating: 5,
        text: "Быстрое пополнение, без проблем. Рекомендую!",
      },
      {
        name: "Ольга С.",
        date: "2026-02-20",
        rating: 4,
        text: "Все прошло гладко, но хотелось бы больше скидок.",
      },
    ],
  },
  
  {
    title: "Arc Raiders",
    image: require("./Images/arc riders.png"),
    price: 799,
    priceLabel: "от 799 руб",
    platform: "Xbox",
    genre: "Action",
    category: "Игры",
    rating: "18+",
    isNew: true,
    discount: 15,
    reviews: [
      {
        name: "Дмитрий К.",
        date: "2026-03-10",
        rating: 5,
        text: "Отличная игра! Захватывающий геймплей.",
      },
      {
        name: "Елена В.",
        date: "2026-03-25",
        rating: 4,
        text: "Хорошая покупка, но графика могла бы быть лучше.",
      },
    ],
  },
  {
    title: "The Last of Us Part I",
    image: require("./Images/The last of Us 2.png"),
    price: 999,
    priceLabel: "от 999 руб",
    platform: "PlayStation",
    genre: "Adventure",
    category: "Игры",
    rating: "18+",
    purchaseOptions: [
      { label: "Standard Edition", price: 999 },
      { label: "Deluxe Edition", price: 1199 },
      { label: "Digital Deluxe", price: 1399 },
    ],
    description:
      "Эксклюзивная игра от Naughty Dog. Полная версия с дополнениями.",
    reviews: [
      {
        name: "Иван П.",
        date: "2026-01-05",
        rating: 5,
        text: "Шедевр! Эмоциональная история и потрясающая графика.",
      },
      {
        name: "Мария Л.",
        date: "2026-02-14",
        rating: 5,
        text: "Лучшая игра года. Стоит каждой копейки.",
      },
    ],
  },
  {
    title: "Xbox Game Pass",
    image: require("./Images/Xbox game pass.png"),
    price: 399,
    priceLabel: "от 399 руб",
    platform: "Xbox",
    genre: "Подписка",
    category: "Подписки",
    rating: "12+",
    purchaseOptions: [
      { label: "1 мес", price: 399 },
      { label: "3 мес", price: 1099 },
      { label: "12 мес", price: 3999 },
    ],
    description: "Подписка Xbox Game Pass — все игры в одном каталоге.",
    reviews: [
      {
        name: "Сергей А.",
        date: "2026-04-01",
        rating: 4,
        text: "Много игр, но некоторые не очень интересные.",
      },
      {
        name: "Анна Т.",
        date: "2026-04-15",
        rating: 5,
        text: "Отличная подписка! Экономит деньги на игры.",
      },
    ],
  },
  {
    title: "OpenAI",
    image: require("./Images/Open AIpng.png"),
    price: 499,
    priceLabel: "от 499 руб",
    platform: "Web",
    genre: "Сервис",
    category: "Подписки",
    rating: "12+",
    purchaseOptions: [
      { label: "1 мес", price: 499 },
      { label: "3 мес", price: 1299 },
      { label: "12 мес", price: 4299 },
    ],
    description: "Подписка OpenAI с доступом к GPT-4 и ChatGPT Plus.",
    reviews: [
      {
        name: "Петр Н.",
        date: "2026-02-28",
        rating: 5,
        text: "GPT-4 потрясающий! Помогает в работе и учебе.",
      },
      {
        name: "Кристина О.",
        date: "2026-03-12",
        rating: 4,
        text: "Хороший сервис, но иногда бывают сбои.",
      },
    ],
  },
  {
    title: "PlayStation Plus",
    image: require("./Images/PlayStation.png"),
    price: 449,
    priceLabel: "от 449 руб",
    platform: "PlayStation",
    genre: "Подписка",
    category: "Подписки",
    rating: "12+",
    purchaseOptions: [
      { label: "1 мес", price: 449 },
      { label: "3 мес", price: 1249 },
      { label: "12 мес", price: 4499 },
    ],
    description: "Подписка PS Plus с онлайн-играми и бонусами.",
    reviews: [
      {
        name: "Владимир З.",
        date: "2026-01-20",
        rating: 5,
        text: "Бесплатные игры каждый месяц — супер!",
      },
      {
        name: "Татьяна Р.",
        date: "2026-02-05",
        rating: 4,
        text: "Хорошая подписка, но цена могла бы быть ниже.",
      },
    ],
  },
  {
    title: "Resident Evil 9",
    image: require("./Images/Resident Evil 9.png"),
    price: 1099,
    priceLabel: "от 1099 руб",
    platform: "PlayStation",
    genre: "Хоррор",
    category: "Игры",
    rating: "18+",
    purchaseOptions: [
      { label: "Standard Edition", price: 1099 },
      { label: "Deluxe Edition", price: 1299 },
    ],
    description: "Новая глава хоррора по знаменитой франшизе.",
    reviews: [
      {
        name: "Андрей Ф.",
        date: "2026-03-30",
        rating: 5,
        text: "Страшная и захватывающая! Лучший RE за долгое время.",
      },
      {
        name: "Наталья Г.",
        date: "2026-04-10",
        rating: 4,
        text: "Хороший хоррор, но концовка могла быть лучше.",
      },
    ],
  },
  {
    title: "Claude AI",
    image: require("./Images/Claude Ai.png"),
    price: 599,
    priceLabel: "от 599 руб",
    platform: "Web",
    genre: "Сервис",
    category: "Подписки",
    rating: "12+",
    options: ["1 мес", "3 мес", "12 мес"],
    reviews: [
      {
        name: "Максим Б.",
        date: "2026-02-10",
        rating: 5,
        text: "Claude очень умный и полезный AI.",
      },
      {
        name: "Юлия Д.",
        date: "2026-03-05",
        rating: 4,
        text: "Хороший альтернатив ChatGPT, но интерфейс мог бы быть лучше.",
      },
    ],
  },
];

const recommendedGames = [
  {
    title: "Toxic Commando",
    image: require("./Images/Toxic Commando.png"),
    price: 599,
    priceLabel: "от 599 руб",
    platform: "Steam/PC",
    genre: "Шутер",
    category: "Игры",
    rating: "18+",
    reviews: [
      {
        name: "Роман С.",
        date: "2026-01-25",
        rating: 4,
        text: "Забавный шутер, но короткий.",
      },
      {
        name: "Екатерина М.",
        date: "2026-02-08",
        rating: 5,
        text: "Очень весело играть с друзьями!",
      },
    ],
  },
  {
    title: "Cyberpunk",
    image: require("./Images/CuberPunk.png"),
    price: 999,
    priceLabel: "от 999 руб",
    platform: "Steam/PC",
    genre: "Action",
    category: "Игры",
    rating: "18+",
    reviews: [
      {
        name: "Артем Л.",
        date: "2026-03-15",
        rating: 5,
        text: "Ночной город потрясающий! Игра года.",
      },
      {
        name: "София К.",
        date: "2026-03-28",
        rating: 4,
        text: "Хорошая игра, но баги в начале.",
      },
    ],
  },
  {
    title: "Marathon",
    image: require("./Images/Marathon.png"),
    price: 749,
    priceLabel: "от 749 руб",
    platform: "Xbox",
    genre: "Спорт",
    category: "Игры",
    rating: "12+",
    reviews: [
      {
        name: "Николай В.",
        date: "2026-02-12",
        rating: 4,
        text: "Реалистичная симуляция бега.",
      },
      {
        name: "Алина П.",
        date: "2026-02-25",
        rating: 5,
        text: "Мотивирует заниматься спортом!",
      },
    ],
  },
  {
    title: "Monster Hunter",
    image: require("./Images/Monster Hunter.png"),
    price: 899,
    priceLabel: "от 899 руб",
    platform: "PlayStation",
    genre: "RPG",
    category: "Игры",
    rating: "16+",
    reviews: [
      {
        name: "Виктор Т.",
        date: "2026-04-05",
        rating: 5,
        text: "Охота на монстров — адреналин!",
      },
      {
        name: "Олеся Р.",
        date: "2026-04-18",
        rating: 4,
        text: "Сложно, но очень интересно.",
      },
    ],
  },
  {
    title: "Crimson Desert",
    image: require("./Images/Crimson Desert.png"),
    price: 899,
    priceLabel: "от 899 руб",
    platform: "Steam/PC",
    reviews: [
      {
        name: "Денис У.",
        date: "2026-01-30",
        rating: 5,
        text: "Красивый мир и глубокий сюжет.",
      },
      {
        name: "Ирина Ф.",
        date: "2026-02-15",
        rating: 4,
        text: "Хорошая RPG, но графика могла бы быть лучше.",
      },
    ],
  },
  {
    title: "Diablo 4",
    image: require("./Images/Diablo 4.png"),
    price: 1099,
    priceLabel: "от 1099 руб",
    platform: "Steam/PC",
    genre: "RPG",
    category: "Игры",
    rating: "18+",
    discount: 20,
    reviews: [
      {
        name: "Станислав Х.",
        date: "2026-03-20",
        rating: 5,
        text: "Diablo вернулся! Уничтожение демонов — кайф.",
      },
      {
        name: "Лариса Е.",
        date: "2026-04-02",
        rating: 4,
        text: "Классика жанра, но онлайн-аспект слабый.",
      },
    ],
  },
  {
    title: "RE Requiem",
    image: require("./Images/Resident Evil 9.png"),
    price: 999,
    priceLabel: "от 999 руб",
    platform: "PlayStation",
    genre: "Хоррор",
    category: "Новинки",
    rating: "18+",
    reviews: [
      {
        name: "Борис Щ.",
        date: "2026-03-05",
        rating: 5,
        text: "Ужас и экшн в одном флаконе!",
      },
      {
        name: "Надежда Ы.",
        date: "2026-03-18",
        rating: 4,
        text: "Страшно, но концовка предсказуема.",
      },
    ],
  },
];

const bestfallGames = [
  {
    title: "Elden Ring",
    image: require("./Images/Elden Ring.png"),
    price: 1199,
    priceLabel: "от 1199 руб",
    platform: "Steam/PC",
    genre: "RPG",
    category: "Игры",
    rating: "18+",
    reviews: [
      {
        name: "Кирилл Ю.",
        date: "2026-01-10",
        rating: 5,
        text: "Мастерская Souls-like! Трудно, но стоит того.",
      },
      {
        name: "Полина Я.",
        date: "2026-01-22",
        rating: 4,
        text: "Красивый мир, но слишком сложно для новичков.",
      },
    ],
  },
  {
    title: "FC26",
    image: require("./Images/FC26.png"),
    price: 1299,
    priceLabel: "от 1299 руб",
    platform: "Steam/PC",
    genre: "Спорт",
    category: "Игры",
    rating: "12+",
    reviews: [
      {
        name: "Александр Э.",
        date: "2026-02-05",
        rating: 5,
        text: "Футбол на высшем уровне!",
      },
      {
        name: "Маргарита Ч.",
        date: "2026-02-18",
        rating: 4,
        text: "Хорошая графика, но управление могло бы быть лучше.",
      },
    ],
  },
  {
    title: "Great Fall",
    image: require("./Images/GreatFall.png"),
    price: 499,
    priceLabel: "от 499 руб",
    platform: "Steam/PC",
    genre: "Action",
    category: "Игры",
    rating: "16+",
    reviews: [
      {
        name: "Олег Ш.",
        date: "2026-03-01",
        rating: 4,
        text: "Забавная игра, но короткая кампания.",
      },
      {
        name: "Светлана Ъ.",
        date: "2026-03-14",
        rating: 5,
        text: "Много уровней и секретов!",
      },
    ],
  },
  {
    title: "GTA V",
    image: require("./Images/GTA V.png"),
    price: 699,
    priceLabel: "от 699 руб",
    platform: "Steam/PC",
    genre: "Action",
    category: "Игры",
    rating: "18+",
    discount: 25,
    reviews: [
      {
        name: "Михаил Ь.",
        date: "2026-04-01",
        rating: 5,
        text: "Классика! Всегда актуально.",
      },
      {
        name: "Антонина Ё.",
        date: "2026-04-15",
        rating: 4,
        text: "Хорошая игра, но мультиплеер устарел.",
      },
    ],
  },
  {
    title: "Resident Evil 4",
    image: require("./Images/RE4.png"),
    price: 899,
    priceLabel: "от 899 руб",
    platform: "PlayStation",
    genre: "Хоррор",
    category: "Игры",
    rating: "18+",
    reviews: [
      {
        name: "Федор Ж.",
        date: "2026-01-28",
        rating: 5,
        text: "Ремейк превосходен! Лучший RE.",
      },
      {
        name: "Людмила З.",
        date: "2026-02-10",
        rating: 4,
        text: "Страшно и интересно, но концовка слабая.",
      },
    ],
  },
  {
    title: "Far Cry 6",
    image: require("./Images/Far Cry 6.png"),
    price: 949,
    priceLabel: "от 949 руб",
    platform: "Steam/PC",
    genre: "Action",
    category: "Игры",
    rating: "18+",
    reviews: [
      {
        name: "Василий Х.",
        date: "2026-03-08",
        rating: 4,
        text: "Хороший экшн, но сюжет предсказуемый.",
      },
      {
        name: "Галина Ц.",
        date: "2026-03-22",
        rating: 5,
        text: "Тропики и революция — огонь!",
      },
    ],
  },
  {
    title: "Red Dead Redemption 2",
    image: require("./Images/RDR 2.png"),
    price: 999,
    priceLabel: "от 999 руб",
    platform: "Steam/PC",
    genre: "Action",
    category: "Игры",
    rating: "18+",
    purchaseOptions: [
      { label: "Standard Edition", price: 999 },
      { label: "Ultimate Edition", price: 1199 },
    ],
    description: "Легендарный вестерн от Rockstar с открытым миром.",
    reviews: [
      {
        name: "Евгений Ч.",
        date: "2026-02-20",
        rating: 5,
        text: "Шедевр! Лучшая игра всех времен.",
      },
      {
        name: "Диана Ш.",
        date: "2026-03-05",
        rating: 5,
        text: "Эмоциональная и красивая история.",
      },
    ],
  },
  {
    title: "Ready or Not",
    image: require("./Images/Ready or not.png"),
    price: 799,
    priceLabel: "от 799 руб",
    platform: "Steam/PC",
    genre: "Шутер",
    category: "Игры",
    rating: "18+",
    reviews: [
      {
        name: "Тимур Щ.",
        date: "2026-04-05",
        rating: 4,
        text: "Реалистичный SWAT симулятор.",
      },
      {
        name: "Регина Ы.",
        date: "2026-04-18",
        rating: 5,
        text: "Кооп с друзьями — лучший!",
      },
    ],
  },
  {
    title: "Valorant",
    image: require("./Images/Valorant.png"),
    price: 299,
    priceLabel: "от 299 руб",
    platform: "Steam/PC",
    genre: "Шутер",
    category: "Игры",
    rating: "16+",
    purchaseOptions: [
      { label: "500 VP", price: 299 },
      { label: "1000 VP", price: 599 },
      { label: "2000 VP", price: 1099 },
    ],
    description: "Покупка валюты Valorant VP для внутриигровых покупок.",
    reviews: [
      {
        name: "Руслан Ь.",
        date: "2026-01-15",
        rating: 5,
        text: "Лучший FPS! Эспорт уровень.",
      },
      {
        name: "Ксения Ё.",
        date: "2026-01-28",
        rating: 4,
        text: "Хорошая игра, но ранговая система жесткая.",
      },
    ],
  },
  {
    title: "Spotify",
    image: require("./Images/Spotify.png"),
    price: 169,
    priceLabel: "от 169 руб",
    platform: "Web",
    genre: "Музыка",
    category: "Подписки",
    rating: "12+",
    purchaseOptions: [
      { label: "1 мес", price: 169 },
      { label: "3 мес", price: 469 },
      { label: "12 мес", price: 1699 },
    ],
    description: "Подписка Spotify Premium без рекламы.",
    reviews: [
      {
        name: "Илья Ж.",
        date: "2026-02-25",
        rating: 5,
        text: "Миллионы треков без рекламы!",
      },
      {
        name: "Вера З.",
        date: "2026-03-10",
        rating: 4,
        text: "Хорошая музыка, но иногда лагает.",
      },
    ],
  },
];

const catalogGamesRaw = [
  ...popularGames,
  ...recommendedGames,
  ...bestfallGames,
];

const catalogGames = Array.from(
  new Map(
    catalogGamesRaw.map((game) => [game.title.trim().toLowerCase(), game]),
  ).values(),
);

export { popularGames, recommendedGames, bestfallGames, catalogGames };
