const popularGames = [
  {
    title: "Пополнение Steam",
    image: require("./Images/div.pop-card.png"),
    price: 299,
    priceLabel: "от 299 руб",
    platform: "PC",
    genre: "Подписка",
    category: "Подписки",
    purchaseOptions: [
      { label: "300 руб", price: 299 },
      { label: "600 руб", price: 599 },
      { label: "1200 руб", price: 1099 },
    ],
    description:
      "Пополнение баланса Steam для покупок в магазине и внутриигровых товаров.",
  },
  {
    title: "Arc Raiders",
    image: require("./Images/arc riders.png"),
    price: 499,
    priceLabel: "от 499 руб",
    platform: "Xbox",
    genre: "Action",
    category: "Игры",
    discount: 15,
  },
  {
    title: "The Last of Us Part I",
    image: require("./Images/The last of Us 2.png"),
    price: 2399,
    priceLabel: "от 2399 руб",
    platform: "PlayStation",
    genre: "Adventure",
    category: "Игры",
    purchaseOptions: [
      { label: "Standard Edition", price: 2399 },
      { label: "Deluxe Edition", price: 2799 },
      { label: "Digital Deluxe", price: 3199 },
    ],
    description:
      "Эксклюзивная игра от Naughty Dog. Полная версия с дополнениями.",
  },
  {
    title: "Xbox Game Pass",
    image: require("./Images/Xbox game pass.png"),
    price: 1999,
    priceLabel: "от 1999 руб",
    platform: "Xbox",
    genre: "Подписка",
    category: "Подписки",
    purchaseOptions: [
      { label: "1 мес", price: 1999 },
      { label: "3 мес", price: 5399 },
      { label: "12 мес", price: 15999 },
    ],
    description: "Подписка Xbox Game Pass — все игры в одном каталоге.",
  },
  {
    title: "OpenAI",
    image: require("./Images/Open AIpng.png"),
    price: 1000,
    priceLabel: "от 1000 руб",
    platform: "Web",
    genre: "Сервис",
    category: "Подписки",
    purchaseOptions: [
      { label: "1 мес", price: 1000 },
      { label: "3 мес", price: 2799 },
      { label: "12 мес", price: 9999 },
    ],
    description: "Подписка OpenAI с доступом к GPT-4 и ChatGPT Plus.",
  },
  {
    title: "PlayStation Plus",
    image: require("./Images/PlayStation.png"),
    price: 2200,
    priceLabel: "от 2200 руб",
    platform: "PlayStation",
    genre: "Подписка",
    category: "Подписки",
    purchaseOptions: [
      { label: "1 мес", price: 2200 },
      { label: "3 мес", price: 6199 },
      { label: "12 мес", price: 21999 },
    ],
    description: "Подписка PS Plus с онлайн-играми и бонусами.",
  },
  {
    title: "Resident Evil 9",
    image: require("./Images/Resident Evil 9.png"),
    price: 2999,
    priceLabel: "от 2999 руб",
    platform: "PlayStation",
    genre: "Хоррор",
    category: "Игры",
    purchaseOptions: [
      { label: "Standard Edition", price: 2999 },
      { label: "Deluxe Edition", price: 3499 },
    ],
    description: "Новая глава хоррора по знаменитой франшизе.",
  },
  {
    title: "Claude AI",
    image: require("./Images/Claude Ai.png"),
    price: 1000,
    priceLabel: "от 1000 руб",
    platform: "Web",
    genre: "Сервис",
    category: "Подписки",
    options: ["1 мес", "3 мес", "12 мес"],
  },
];

const recommendedGames = [
  {
    title: "Toxic Commando",
    image: require("./Images/Toxic Commando.png"),
    price: 899,
    priceLabel: "от 899 руб",
    platform: "PC",
    genre: "Шутер",
    category: "Игры",
  },
  {
    title: "Cyberpunk",
    image: require("./Images/CuberPunk.png"),
    price: 2299,
    priceLabel: "от 2299 руб",
    platform: "PC",
    genre: "Action",
    category: "Игры",
  },
  {
    title: "Marathon",
    image: require("./Images/Marathon.png"),
    price: 1999,
    priceLabel: "от 1999 руб",
    platform: "Xbox",
    genre: "Спорт",
    category: "Игры",
  },
  {
    title: "Monster Hunter",
    image: require("./Images/Monster Hunter.png"),
    price: 1500,
    priceLabel: "от 1500 руб",
    platform: "PlayStation",
    genre: "RPG",
    category: "Игры",
  },
  {
    title: "Crimson Desert",
    image: require("./Images/Crimson Desert.png"),
    price: 1699,
    priceLabel: "от 1699 руб",
    platform: "PC",
    genre: "Action",
    category: "Игры",
  },
  {
    title: "Diablo 4",
    image: require("./Images/Diablo 4.png"),
    price: 2599,
    priceLabel: "от 2599 руб",
    platform: "PC",
    genre: "RPG",
    category: "Игры",
    discount: 20,
  },
  {
    title: "Crimson Desert",
    image: require("./Images/Crimson Desert.png"),
    price: 1699,
    priceLabel: "от 1699 руб",
    platform: "PC",
    genre: "Action",
    category: "Новинки",
  },
  {
    title: "RE Requiem",
    image: require("./Images/Resident Evil 9.png"),
    price: 2799,
    priceLabel: "от 2799 руб",
    platform: "PlayStation",
    genre: "Хоррор",
    category: "Новинки",
  },
];

const bestfallGames = [
  {
    title: "Elden Ring",
    image: require("./Images/Elden Ring.png"),
    price: 2999,
    priceLabel: "от 2999 руб",
    platform: "PC",
    genre: "RPG",
    category: "Игры",
  },
  {
    title: "FC26",
    image: require("./Images/FC26.png"),
    price: 3999,
    priceLabel: "от 3999 руб",
    platform: "PC",
    genre: "Спорт",
    category: "Игры",
  },
  {
    title: "Great Fall",
    image: require("./Images/GreatFall.png"),
    price: 899,
    priceLabel: "от 899 руб",
    platform: "PC",
    genre: "Action",
    category: "Игры",
  },
  {
    title: "GTA V",
    image: require("./Images/GTA V.png"),
    price: 999,
    priceLabel: "от 999 руб",
    platform: "PC",
    genre: "Action",
    category: "Игры",
    discount: 25,
  },
  {
    title: "Resident Evil 4",
    image: require("./Images/RE4.png"),
    price: 1999,
    priceLabel: "от 1999 руб",
    platform: "PlayStation",
    genre: "Хоррор",
    category: "Игры",
  },
  {
    title: "Far Cry 6",
    image: require("./Images/Far Cry 6.png"),
    price: 2199,
    priceLabel: "от 2199 руб",
    platform: "PC",
    genre: "Action",
    category: "Игры",
  },
  {
    title: "Red Dead Redemption 2",
    image: require("./Images/RDR 2.png"),
    price: 1899,
    priceLabel: "от 1899 руб",
    platform: "PC",
    genre: "Action",
    category: "Игры",
    purchaseOptions: [
      { label: "Standard Edition", price: 1899 },
      { label: "Ultimate Edition", price: 2199 },
    ],
    description: "Легендарный вестерн от Rockstar с открытым миром.",
  },
  {
    title: "Ready or Not",
    image: require("./Images/Ready or not.png"),
    price: 2299,
    priceLabel: "от 2299 руб",
    platform: "PC",
    genre: "Шутер",
    category: "Игры",
  },
  {
    title: "Valorant",
    image: require("./Images/Valorant.png"),
    price: 499,
    priceLabel: "от 499 руб",
    platform: "PC",
    genre: "Шутер",
    category: "Игры",
    purchaseOptions: [
      { label: "500 VP", price: 499 },
      { label: "1000 VP", price: 899 },
      { label: "2000 VP", price: 1699 },
    ],
    description: "Покупка валюты Valorant VP для внутриигровых покупок.",
  },
  {
    title: "Spotify",
    image: require("./Images/Spotify.png"),
    price: 299,
    priceLabel: "от 299 руб",
    platform: "Web",
    genre: "Музыка",
    category: "Подписки",
    purchaseOptions: [
      { label: "1 мес", price: 299 },
      { label: "3 мес", price: 799 },
      { label: "12 мес", price: 2799 },
    ],
    description: "Подписка Spotify Premium без рекламы.",
  },
];

const catalogGamesRaw = [
  ...popularGames,
  ...recommendedGames,
  ...bestfallGames,
];

const catalogGames = Array.from(
  new Map(
    catalogGamesRaw.map((game) => [game.title.trim().toLowerCase(), game]),
  ).values(),
);

export { popularGames, recommendedGames, bestfallGames, catalogGames };
